version: '3.9'
services:
  npm:
    image: node:18-alpine
    working_dir: /app
    entrypoint: npm
    ports:
      - '3000:3000'
    volumes:
      - ../../:/app
    environment:
      - NODE_ENV=development
